// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB18281Budxh4mXJXmTQybl4dmNvQgtrq8',
    appId: '1:370067865961:web:11d93b9723140255e97df8',
    messagingSenderId: '370067865961',
    projectId: 'first-responder-network',
    authDomain: 'first-responder-network.firebaseapp.com',
    storageBucket: 'first-responder-network.firebasestorage.app',
    measurementId: 'G-E48HQX8KK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWEw5188AQlG7CLaGNTb4Irf00ypf9qQw',
    appId: '1:370067865961:android:91c69f1fe39fc1b6e97df8',
    messagingSenderId: '370067865961',
    projectId: 'first-responder-network',
    storageBucket: 'first-responder-network.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeuBBOmVP7WrdPfjWwAeRnG1HTAS57yh4',
    appId: '1:370067865961:ios:61a9558eb9030395e97df8',
    messagingSenderId: '370067865961',
    projectId: 'first-responder-network',
    storageBucket: 'first-responder-network.firebasestorage.app',
    iosBundleId: 'com.example.firstresponderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeuBBOmVP7WrdPfjWwAeRnG1HTAS57yh4',
    appId: '1:370067865961:ios:61a9558eb9030395e97df8',
    messagingSenderId: '370067865961',
    projectId: 'first-responder-network',
    storageBucket: 'first-responder-network.firebasestorage.app',
    iosBundleId: 'com.example.firstresponderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB18281Budxh4mXJXmTQybl4dmNvQgtrq8',
    appId: '1:370067865961:web:e9571281ae8ff4fee97df8',
    messagingSenderId: '370067865961',
    projectId: 'first-responder-network',
    authDomain: 'first-responder-network.firebaseapp.com',
    storageBucket: 'first-responder-network.firebasestorage.app',
    measurementId: 'G-F9EEKNEY1M',
  );
}
